name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python3 -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  macos:
    name: Build and Test on macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python3 -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  windows-random:
    name: Build and Test on Windows (Ninja and random compiler)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  windows-vs:
    name: Build and Test on Windows (Visual Studio)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: python -m pip install meson~=1.2.2 ninja~=1.11.1

      - name: Setup build with Meson
        run: meson setup -Dvsenv=true build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build
